Update testhelmworkflows.yml

diff --git a/.github/workflows/testhelmworkflows.yml b/.github/workflows/testhelmworkflows.yml
--- a/.github/workflows/testhelmworkflows.yml
+++ b/.github/workflows/testhelmworkflows.yml
@@ -48,7 +48,7 @@ env:
   CLUSTER_NAME: test-helm-workflow
   DOCKER_FILE: ./Dockerfile
   BUILD_CONTEXT_PATH: ./
-  CHART_PATH: ./templates
+  CHART_PATH: ./
   CHART_OVERRIDE_PATH: ./values.yaml
   CHART_OVERRIDES: image.repository='acrworkflow1729549671164.azurecr.io/image-workflow-1729549671164'
   NAMESPACE: namespace-workflow-1729549671164
@@ -115,6 +115,10 @@ jobs:
         run: |
           result=$(az aks show --resource-group ${{ env.CLUSTER_RESOURCE_GROUP }} --name ${{ env.CLUSTER_NAME }} --query "apiServerAccessProfile.enablePrivateCluster")
           echo "PRIVATE_CLUSTER=$result" >> "$GITHUB_OUTPUT"
+          if [ $result != 'true' && $result != 'false' && result != '' ]; then
+            echo "private cluster result is invalid: $result"
+            exit 1
+          fi
 
       # Deploys application
       - name: Deploy application on private cluster
